FROM registry.access.redhat.com/ubi8/go-toolset:1.16.12 AS builder

# Bring in the go dependencies before anything else so we can take
# advantage of caching these layers in future builds.
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . .
RUN make build

FROM registry.access.redhat.com/ubi8/ubi-micro

COPY --from=builder /opt/app-root/src/build/init_container /usr/bin/init_run

ENTRYPOINT ["/usr/bin/init_run"]
